# Generated by Django 4.2.3 on 2023-08-10 10:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_alter_seller_seller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_id',
            field=models.UUIDField(default=uuid.UUID('017f6f97-8a1c-4029-a99d-0ef88e8457a8'), editable=False, primary_key=True, serialize=False),
        ),
    ]
