# Generated by Django 4.2.3 on 2023-08-10 10:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_alter_seller_seller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_id',
            field=models.UUIDField(default=uuid.UUID('019392b4-f324-4eff-a85e-fc977080e639'), editable=False, primary_key=True, serialize=False),
        ),
    ]
