# Generated by Django 4.2.3 on 2023-08-15 10:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_alter_seller_seller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_id',
            field=models.UUIDField(default=uuid.UUID('0069acf2-c833-4127-a0df-e5aca4a90eca'), editable=False, primary_key=True, serialize=False),
        ),
    ]
