# Generated by Django 4.2.3 on 2023-08-15 11:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_alter_seller_seller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_id',
            field=models.UUIDField(default=uuid.UUID('559310d9-3264-4de5-aa80-f83d2db655b8'), editable=False, primary_key=True, serialize=False),
        ),
    ]
