# Generated by Django 4.2.3 on 2023-08-15 12:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0008_alter_seller_seller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_id',
            field=models.UUIDField(default=uuid.UUID('70951ad3-2a06-4e2b-a71c-afcea13d3d87'), editable=False, primary_key=True, serialize=False),
        ),
    ]
