# Generated by Django 4.2.3 on 2023-08-15 12:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0010_alter_seller_seller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_id',
            field=models.UUIDField(default=uuid.UUID('099db8dd-31e8-45c2-980c-e82f41d4d682'), editable=False, primary_key=True, serialize=False),
        ),
    ]
