# Generated by Django 4.2.3 on 2023-08-15 13:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0012_alter_seller_seller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_id',
            field=models.UUIDField(default=uuid.UUID('49a44350-302a-4b3e-8f6e-b39053132ad9'), editable=False, primary_key=True, serialize=False),
        ),
    ]
