# Generated by Django 4.2.3 on 2023-08-15 13:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0013_alter_seller_seller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_id',
            field=models.UUIDField(default=uuid.UUID('59d60fe3-f325-403f-aec9-60b3f9defde1'), editable=False, primary_key=True, serialize=False),
        ),
    ]
