# Generated by Django 4.2.3 on 2023-08-15 13:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0014_alter_seller_seller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_id',
            field=models.UUIDField(default=uuid.UUID('87a3fcda-aab6-41b6-848b-3af5b0048720'), editable=False, primary_key=True, serialize=False),
        ),
    ]
