# Generated by Django 4.2.3 on 2023-08-15 14:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0016_alter_seller_seller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_id',
            field=models.UUIDField(default=uuid.UUID('8f2c6ae1-f283-4706-98fc-c653e6c694d1'), editable=False, primary_key=True, serialize=False),
        ),
    ]
