# Generated by Django 4.2.3 on 2023-08-15 14:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0018_alter_seller_seller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_id',
            field=models.UUIDField(default=uuid.UUID('1a90e6ed-6dfe-4216-9e79-f5b6c3f8bc48'), editable=False, primary_key=True, serialize=False),
        ),
    ]
