# Generated by Django 4.2.3 on 2023-08-15 14:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0019_alter_seller_seller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_id',
            field=models.UUIDField(default=uuid.UUID('6be3c0c5-1253-4a26-9495-db50b62b70a2'), editable=False, primary_key=True, serialize=False),
        ),
    ]
