# Generated by Django 4.2.3 on 2023-08-15 14:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0020_alter_seller_seller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_id',
            field=models.UUIDField(default=uuid.UUID('af51c8a7-693e-4bd0-a7a8-91ed37d0ccfc'), editable=False, primary_key=True, serialize=False),
        ),
    ]
