# Generated by Django 4.2.3 on 2023-08-15 14:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0021_alter_seller_seller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_id',
            field=models.UUIDField(default=uuid.UUID('323a6cc7-6af8-4665-9dad-e9351dbeb8b3'), editable=False, primary_key=True, serialize=False),
        ),
    ]
