# Generated by Django 4.2.3 on 2023-08-16 08:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0023_alter_seller_seller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_id',
            field=models.UUIDField(default=uuid.UUID('8061ba32-745e-4f96-af53-e056ad4cfa78'), editable=False, primary_key=True, serialize=False),
        ),
    ]
