# Generated by Django 4.2.3 on 2023-08-16 08:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0025_alter_seller_seller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_id',
            field=models.UUIDField(default=uuid.UUID('a7febf7d-9cac-4ae6-bbde-e3dc592ad1fe'), editable=False, primary_key=True, serialize=False),
        ),
    ]
