# Generated by Django 4.2.3 on 2023-08-16 10:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0027_alter_seller_seller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_id',
            field=models.UUIDField(default=uuid.UUID('b6d5a9b1-215b-459c-b40c-070d86575221'), editable=False, primary_key=True, serialize=False),
        ),
    ]
