# Generated by Django 4.2.3 on 2023-08-16 15:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0029_alter_seller_seller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_id',
            field=models.UUIDField(default=uuid.UUID('2860c784-e58f-4d6f-9178-e397da562847'), editable=False, primary_key=True, serialize=False),
        ),
    ]
