# Generated by Django 4.2.3 on 2023-08-16 15:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0031_alter_seller_seller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_id',
            field=models.UUIDField(default=uuid.UUID('e04e242f-b3f4-4e0d-ae7c-29413876a1b2'), editable=False, primary_key=True, serialize=False),
        ),
    ]
