# Generated by Django 4.2.3 on 2023-09-18 05:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0033_alter_seller_seller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_id',
            field=models.UUIDField(default=uuid.UUID('02f8ed13-d288-4287-981b-cfea5ad2c42b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
