# Generated by Django 4.2.3 on 2023-09-18 06:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0034_alter_seller_seller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_id',
            field=models.UUIDField(default=uuid.UUID('30da72ea-93df-4fb1-9d91-3a5c0f6ed096'), editable=False, primary_key=True, serialize=False),
        ),
    ]
