# Generated by Django 4.2.3 on 2023-09-28 10:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0037_alter_seller_seller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_id',
            field=models.UUIDField(default=uuid.UUID('e038fe8d-7edd-4a6f-ba7d-01c6326959d3'), editable=False, primary_key=True, serialize=False),
        ),
    ]
