# Generated by Django 4.2.3 on 2023-09-28 10:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0039_alter_seller_seller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_id',
            field=models.UUIDField(default=uuid.UUID('3051f55c-9237-4a61-935d-1f773bd785e4'), editable=False, primary_key=True, serialize=False),
        ),
    ]
