# Generated by Django 4.2.3 on 2023-09-28 10:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0040_alter_seller_seller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_id',
            field=models.UUIDField(default=uuid.UUID('db5c7ae2-5659-4549-814f-4ccb9f015bb9'), editable=False, primary_key=True, serialize=False),
        ),
    ]
