# Generated by Django 4.2.3 on 2023-09-18 05:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('504d4c77-fe15-46a2-a26f-9b0cfdd6c85d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
