# Generated by Django 4.2.3 on 2023-09-26 11:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('2f0959b4-0f3b-4632-a950-d56e3bc43dd8'), editable=False, primary_key=True, serialize=False),
        ),
    ]
