# Generated by Django 4.2.3 on 2023-09-28 10:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('dc2205d6-6b1d-46f5-99e0-a9c85b1b9503'), editable=False, primary_key=True, serialize=False),
        ),
    ]
