# Generated by Django 4.2.3 on 2023-09-28 10:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('bbcf0b67-b22d-4aa2-8e3b-398090e27871'), editable=False, primary_key=True, serialize=False),
        ),
    ]
