# Generated by Django 4.2.3 on 2023-09-28 10:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('6c257647-5f37-40ed-8e41-e73f89a30c58'), editable=False, primary_key=True, serialize=False),
        ),
    ]
