# Generated by Django 4.2.3 on 2023-09-28 10:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('1b8d0dcb-884e-4ebd-ade3-31d385ad355b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
