# Generated by Django 4.2.3 on 2023-09-28 11:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0043_alter_seller_seller_id'),
        ('user', '0010_alter_user_user_id'),
        ('products', '0039_alter_brand_brand_id_alter_category_cat_id_and_more'),
        ('orders', '0002_delete_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('units', models.IntegerField()),
                ('total_price', models.FloatField(editable=False)),
                ('pro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.seller')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
