# Generated by Django 4.2.3 on 2023-09-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_cart_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='avaliable',
            field=models.CharField(default='Na', editable=False),
        ),
    ]
