# Generated by Django 4.2.3 on 2023-10-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_wishlist_avaliable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='avaliable',
            field=models.CharField(default='Na', editable=False, max_length=100),
        ),
    ]
