# Generated by Django 4.2.3 on 2023-08-06 08:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_id',
            field=models.UUIDField(default=uuid.UUID('6465f8e0-8888-4230-b81f-f9e9a986e4ee'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_id',
            field=models.UUIDField(default=uuid.UUID('dd1bd3eb-7784-4e12-8e5d-afe12502feee'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='sub_id',
            field=models.UUIDField(default=uuid.UUID('b062677a-aec6-4b6c-9fd9-7d2e24d9f689'), editable=False, primary_key=True, serialize=False),
        ),
    ]
