# Generated by Django 4.2.3 on 2023-08-06 08:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_brand_brand_id_alter_category_cat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_id',
            field=models.UUIDField(default=uuid.UUID('aae84fb4-0b95-4538-866e-adfc118934c1'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_id',
            field=models.UUIDField(default=uuid.UUID('028eb251-74b5-4bc9-bcd7-351e12273860'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='sub_id',
            field=models.UUIDField(default=uuid.UUID('1b929c98-4d13-4aa2-bcfd-4360340d41a9'), editable=False, primary_key=True, serialize=False),
        ),
    ]
