# Generated by Django 4.2.3 on 2023-08-07 10:35

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
        ('products', '0003_alter_brand_brand_id_alter_category_cat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_id',
            field=models.UUIDField(default=uuid.UUID('1309af05-815c-414e-9521-dce5f47fb596'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_id',
            field=models.UUIDField(default=uuid.UUID('7820746c-f1b3-4655-a06d-f30113cdd568'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='sub_id',
            field=models.UUIDField(default=uuid.UUID('9ba37ec5-4cb8-48a6-9b64-52a60c2a2c94'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('listed_date', models.DateTimeField(auto_created=True)),
                ('pro_id', models.UUIDField(default=uuid.UUID('30dc9c9e-c378-4d75-9bf7-458a70040be9'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('image_data', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=225), size=None)),
                ('variant', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=10)),
                ('discount_offers', models.CharField(max_length=5)),
                ('product_code', models.CharField(max_length=225)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('availability', models.CharField(max_length=10)),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.brand')),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.seller')),
                ('sub_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.subcategory')),
            ],
        ),
    ]
