# Generated by Django 4.2.3 on 2023-08-10 10:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_brand_brand_id_alter_category_cat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_id',
            field=models.UUIDField(default=uuid.UUID('e2947ee7-f12c-4676-91a4-1e4390570eb9'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_id',
            field=models.UUIDField(default=uuid.UUID('45c14868-3d09-42f1-b7cd-d751b6d9f953'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='pro_id',
            field=models.UUIDField(default=uuid.UUID('b2fd15c1-5011-4ecc-a977-dfd91f9b6cf5'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='sub_id',
            field=models.UUIDField(default=uuid.UUID('141338aa-c5a0-4af4-95ca-c5b5fd5b632d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
