# Generated by Django 4.2.3 on 2023-08-10 10:55

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_brand_brand_id_alter_category_cat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_id',
            field=models.UUIDField(default=uuid.UUID('f4533c1e-5a7d-42af-b4c6-14079e80078b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_id',
            field=models.UUIDField(default=uuid.UUID('cc3698bd-69d6-4a27-ac7e-6950e3544fcb'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='image_data',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), size=None),
        ),
        migrations.AlterField(
            model_name='products',
            name='listed_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='pro_id',
            field=models.UUIDField(default=uuid.UUID('bff06b1e-d6f0-4b8f-9761-403b9f512e10'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='sub_id',
            field=models.UUIDField(default=uuid.UUID('d7cc0b36-6860-4ca9-9928-fab7a255f946'), editable=False, primary_key=True, serialize=False),
        ),
    ]
