# Generated by Django 4.2.3 on 2023-08-10 10:57

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_brand_brand_id_alter_category_cat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_id',
            field=models.UUIDField(default=uuid.UUID('cb7be5a5-1467-4227-8a50-04b188d9f7ec'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_id',
            field=models.UUIDField(default=uuid.UUID('fa1a2397-304d-4137-9501-d7ebd319c5ec'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='image_data',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), size=None),
        ),
        migrations.AlterField(
            model_name='products',
            name='pro_id',
            field=models.UUIDField(default=uuid.UUID('6491d41b-1041-42b9-9691-e659726a44ac'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='sub_id',
            field=models.UUIDField(default=uuid.UUID('39cbf96b-cc4f-45be-a3e3-31011b3e4afc'), editable=False, primary_key=True, serialize=False),
        ),
    ]
