# Generated by Django 4.2.3 on 2023-08-15 11:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_brand_brand_id_alter_category_cat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_id',
            field=models.UUIDField(default=uuid.UUID('3242b2d4-89c2-4f25-9b94-4a9b2fd1f80f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_id',
            field=models.UUIDField(default=uuid.UUID('64d3c275-5a41-46a0-9270-27bdc41c413b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='pro_id',
            field=models.UUIDField(default=uuid.UUID('5a9bb21e-9ca9-44f6-8dae-985559038a90'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='sub_id',
            field=models.UUIDField(default=uuid.UUID('7b7e244b-acbf-4249-9ece-f14e3a134a64'), editable=False, primary_key=True, serialize=False),
        ),
    ]
