# Generated by Django 4.2.3 on 2023-08-15 12:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_brand_brand_id_alter_category_cat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_id',
            field=models.UUIDField(default=uuid.UUID('592f482b-0c5b-499d-b2d9-db088bdb20fe'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_id',
            field=models.UUIDField(default=uuid.UUID('b8c9e9ff-b905-4312-ba54-6ff6b43ac0ea'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='pro_id',
            field=models.UUIDField(default=uuid.UUID('8a07d04e-4829-47b7-9251-b5f011194fa0'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='sub_id',
            field=models.UUIDField(default=uuid.UUID('6c976946-2664-487a-9c6d-33aaccbcf2b0'), editable=False, primary_key=True, serialize=False),
        ),
    ]
