# Generated by Django 4.2.3 on 2023-08-15 13:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_brand_brand_id_alter_category_cat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_id',
            field=models.UUIDField(default=uuid.UUID('5742e905-b395-46b0-9a45-0a310e1a4802'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_id',
            field=models.UUIDField(default=uuid.UUID('05f403ca-597e-4d1d-8c37-defb73d52797'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='pro_id',
            field=models.UUIDField(default=uuid.UUID('90fc3a17-c443-4ed9-84f5-72d6a0334665'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='sub_id',
            field=models.UUIDField(default=uuid.UUID('5f56d8a6-aaa2-424d-b8e9-ab9536b4cf8c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
