# Generated by Django 4.2.3 on 2023-08-15 13:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_brand_brand_id_alter_category_cat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_id',
            field=models.UUIDField(default=uuid.UUID('f96e8515-8d74-43b3-bb4b-1e5e9bdbd941'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_id',
            field=models.UUIDField(default=uuid.UUID('36bf0319-6553-45c0-b276-346e8dc7dabc'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='pro_id',
            field=models.UUIDField(default=uuid.UUID('690d7bcf-49d4-4d42-81e6-538e7add750c'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='sub_id',
            field=models.UUIDField(default=uuid.UUID('2bd95593-9c16-4f4f-a5d8-3c2909c5b013'), editable=False, primary_key=True, serialize=False),
        ),
    ]
