# Generated by Django 4.2.3 on 2023-08-15 14:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_brand_brand_id_alter_category_cat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_id',
            field=models.UUIDField(default=uuid.UUID('4a31fa6a-4e6b-4578-accd-5b7469ebe2eb'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_id',
            field=models.UUIDField(default=uuid.UUID('de1f85d2-e7d0-4b04-9789-4af9e04713d2'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='pro_id',
            field=models.UUIDField(default=uuid.UUID('4f4caf36-3bf4-4263-a114-b6e5051a1b31'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='sub_id',
            field=models.UUIDField(default=uuid.UUID('01bb53c8-eccd-430c-874b-929cc0fd10af'), editable=False, primary_key=True, serialize=False),
        ),
    ]
