# Generated by Django 4.2.3 on 2023-08-15 14:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_brand_brand_id_alter_category_cat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_id',
            field=models.UUIDField(default=uuid.UUID('4ab07bd0-a073-4bd8-b383-b17fc8bf403a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_id',
            field=models.UUIDField(default=uuid.UUID('68d1d081-03cf-4c9d-9f2a-4f0aff4e7db0'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='pro_id',
            field=models.UUIDField(default=uuid.UUID('c924c6af-5484-42c9-bbdc-d6caf5ed222c'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='sub_id',
            field=models.UUIDField(default=uuid.UUID('e2e2ed20-4280-401c-94e2-f49b3af0a0b1'), editable=False, primary_key=True, serialize=False),
        ),
    ]
