# Generated by Django 4.2.3 on 2023-08-16 08:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_alter_brand_brand_id_alter_category_cat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_id',
            field=models.UUIDField(default=uuid.UUID('0a75af1f-eaeb-4a78-8276-a02ae2d45cb7'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_id',
            field=models.UUIDField(default=uuid.UUID('9d265363-f850-4e69-8e8d-6d22388cc01b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='pro_id',
            field=models.UUIDField(default=uuid.UUID('7a881655-58d0-4485-a8c7-478155aa7c5f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='sub_id',
            field=models.UUIDField(default=uuid.UUID('e829b912-78bf-46ba-89d6-e136e8e56abe'), editable=False, primary_key=True, serialize=False),
        ),
    ]
