# Generated by Django 4.2.3 on 2023-08-16 08:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_alter_brand_brand_id_alter_category_cat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_id',
            field=models.UUIDField(default=uuid.UUID('439a1d07-3e40-4817-83d2-ecd4d7eb2b76'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_id',
            field=models.UUIDField(default=uuid.UUID('9cf9e7db-2d5c-49ee-a9bb-836f8f833315'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='pro_id',
            field=models.UUIDField(default=uuid.UUID('50d3281a-0498-49b1-9832-d5b2ceba4590'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='sub_id',
            field=models.UUIDField(default=uuid.UUID('dba06f15-0da2-45e6-bc27-af84d7878440'), editable=False, primary_key=True, serialize=False),
        ),
    ]
