# Generated by Django 4.2.3 on 2023-08-16 10:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_alter_brand_brand_id_alter_category_cat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_id',
            field=models.UUIDField(default=uuid.UUID('20f81e82-5010-4c8a-b73c-969eca1cf0d3'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_id',
            field=models.UUIDField(default=uuid.UUID('d835e78d-83e9-4cb4-aa4e-ec542fd8d077'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='pro_id',
            field=models.UUIDField(default=uuid.UUID('fa7eb3d7-51ed-4345-9e76-5bfb03baa342'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='sub_id',
            field=models.UUIDField(default=uuid.UUID('9378673d-cb58-4c19-b467-5070ddbb38af'), editable=False, primary_key=True, serialize=False),
        ),
    ]
