# Generated by Django 4.2.3 on 2023-09-18 05:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_alter_brand_brand_id_alter_category_cat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_id',
            field=models.UUIDField(default=uuid.UUID('6268afc1-208d-4076-ba73-2c6582740f14'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_id',
            field=models.UUIDField(default=uuid.UUID('37d2789e-fea4-4c65-97bf-7ec3fa76d8e7'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='pro_id',
            field=models.UUIDField(default=uuid.UUID('aec653e2-9824-49a7-9606-3fd9eaebfde2'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='sub_id',
            field=models.UUIDField(default=uuid.UUID('78e79c2e-0ab9-43dd-b426-108b05e840af'), editable=False, primary_key=True, serialize=False),
        ),
    ]
